# Generated by Django 4.2.16 on 2024-11-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='cvc',
            field=models.CharField(blank=True, default='000', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='fechaVencimiento',
            field=models.DateField(blank=True, default='2022-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='saldoActual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='saldoInicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
