# Generated by Django 4.2.16 on 2024-11-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_cuentabancaria_cvc_cuentabancaria_fechavencimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='afilacion',
            field=models.CharField(choices=[('Visa', 'Visa'), ('MasterCard', 'MasterCard'), ('American Express', 'American Express'), ('Discover', 'Discover'), ('Otra', 'Otra')], default='Otra'),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='tipoCuenta',
            field=models.CharField(choices=[('Credito', 'Crédito'), ('Debito', 'Débito'), ('Cheques', 'Cheques')]),
        ),
    ]
