# Generated by Django 4.2.16 on 2024-11-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_egreso_descripcion_ingreso_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='deuda',
            name='fecha_vencimiento',
            field=models.DateField(default='2022-01-01'),
        ),
    ]
