# Generated by Django 4.2.16 on 2024-11-08 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_egreso_tipo_ingreso_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='fechaIngreso',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
