# Generated by Django 4.2.16 on 2024-11-10 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_egreso_fechaingreso_ingreso_fechaingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deuda',
            name='tarjeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.cuentabancaria'),
        ),
    ]
