# Generated by Django 4.2.16 on 2024-11-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_deuda_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
