# Generated by Django 4.2.16 on 2024-11-14 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0011_prestamo_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetacredito',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas_credito', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
