# Generated by Django 4.2.16 on 2024-11-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_tarjetacredito_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
