# Generated by Django 4.2.16 on 2024-11-15 00:54

import dashboard.utils.validation
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0015_banco_created_at_banco_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banco',
            options={'ordering': ['nombre'], 'verbose_name': 'Banco', 'verbose_name_plural': 'Bancos'},
        ),
        migrations.AlterModelOptions(
            name='cuentabancaria',
            options={'ordering': ['nombre'], 'verbose_name': 'Cuenta Bancaria', 'verbose_name_plural': 'Cuentas Bancarias'},
        ),
        migrations.AlterModelOptions(
            name='deuda',
            options={'ordering': ['fecha_vencimiento'], 'verbose_name': 'Deuda', 'verbose_name_plural': 'Deudas'},
        ),
        migrations.AlterModelOptions(
            name='egreso',
            options={'ordering': ['fecha'], 'verbose_name': 'Egreso', 'verbose_name_plural': 'Egresos'},
        ),
        migrations.AlterModelOptions(
            name='prestamo',
            options={'ordering': ['fecha_inicio'], 'verbose_name': 'Préstamo', 'verbose_name_plural': 'Préstamos'},
        ),
        migrations.AlterModelOptions(
            name='tarjetacredito',
            options={'ordering': ['nombre_titular'], 'verbose_name': 'Tarjeta de Crédito', 'verbose_name_plural': 'Tarjetas de Crédito'},
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='fechaIngreso',
        ),
        migrations.AlterField(
            model_name='banco',
            name='telefono',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'El número de teléfono debe ser de 9 a 15 dígitos.')]),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='afilacion',
            field=models.CharField(choices=[('Visa', 'Visa'), ('MasterCard', 'MasterCard'), ('American Express', 'American Express'), ('Discover', 'Discover'), ('Otra', 'Otra')], default='Otra', max_length=20),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='cvc',
            field=models.CharField(blank=True, default='000', max_length=3, null=True, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'El CVC debe ser un número de 3 dígitos.')]),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='fechaVencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='saldoActual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='saldoInicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='tipoCuenta',
            field=models.CharField(choices=[('Credito', 'Crédito'), ('Debito', 'Débito'), ('Cheques', 'Cheques')], max_length=10),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='fecha_vencimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[dashboard.utils.validation.validate_positive]),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[dashboard.utils.validation.validate_positive]),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='tasa_interes',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='limite',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='numero_tarjeta',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'El número de tarjeta debe contener 16 dígitos.')]),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación')], max_length=10)),
                ('record_id', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
    ]
