# Generated by Django 5.1.3 on 2024-11-19 20:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_banco_cobro_mantenimiento_banco_cobro_pago_minimo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meses', models.PositiveIntegerField()),
                ('porcentaje_interes', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasas_interes', to='dashboard.banco')),
            ],
            options={
                'verbose_name': 'Tasa de Interés',
                'verbose_name_plural': 'Tasas de Interés',
                'ordering': ['banco', 'meses'],
                'unique_together': {('banco', 'meses')},
            },
        ),
    ]
