# Generated by Django 5.1.3 on 2024-11-20 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_tasainteres_fechacorte'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasainteres',
            name='fechaLimite',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
