# Generated by Django 5.1.3 on 2024-11-20 18:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_tarjetacredito_limite_maximo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deuda',
            name='interes',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='deuda',
            name='meses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='tipo_deuda',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('tarjeta', 'Tarjeta de Crédito'), ('prestamo', 'Préstamo'), ('meses', 'Deuda a Meses')], default='tarjeta', max_length=50),
        ),
        migrations.CreateModel(
            name='DeudaMeses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tipo_deuda', models.CharField(choices=[('usuario', 'Usuario'), ('tarjeta', 'Tarjeta de Crédito'), ('prestamo', 'Préstamo')], max_length=60)),
                ('estado', models.BooleanField(default=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('meses', models.PositiveIntegerField()),
                ('interes', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('prestamo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.prestamo')),
                ('tarjeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.cuentabancaria')),
                ('usuario_deudor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas_meses_deudor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deuda a Meses',
                'verbose_name_plural': 'Deudas a Meses',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.AddField(
            model_name='deuda',
            name='deuda_meses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.deudameses'),
        ),
    ]
